server:
  port: 8001

spring:
  profiles:
    active: default
  application:
    name: user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogsite
    username: root
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true


