server:
  port: 8011
  application:
    name: blog-replica
  data:
    mongodb:
      uri: mongodb+srv://nareshkumar546nk:Password@mongocluster.3khr6ur.mongodb.net/
#      port: 27017
#      host: localhost
      database: blogReadDb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_3PQhzGhke
user:
  replica:
    url: http://USER-REPLICA/api/v1.0/blogsite/users/
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
