server:
  port: 8000
spring:
  application:
    name: Blog-Site
  datasource:
    url: jdbc:mysql://blog-site-database.ckzrz1mw2ejg.us-east-1.rds.amazonaws.com:3306/blogs
    username: root
    password: Password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true

#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect