server:
  port: 8000
spring:
  application:
    name: Blog-Site
  data:
    mongodb:
      uri: mongodb+srv://nareshkumar546nk:Password@mongocluster.3khr6ur.mongodb.net/
      database: blogReadDb
#    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect