server:
  port: 8010

spring:
  profiles:
    active: default
  application:
    name: blog
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogsite
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_3PQhzGhke

