server:
  port: 8010

spring:
  profiles:
    active: default
  application:
    name: blog
  datasource:
#    url: jdbc:h2:mem:?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/blogsite?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_3PQhzGhke
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#
#logging:
#  file:
#    name: ${logging.file.path}/blog.log
#    path: E:/Practics/EAccedamy-project/Blog-backend-project/Log
#  pattern:
#    rolling-file-name: ${logging.file.path}/blog-%d{yyyy-MM-dd}.%i.log
#    file:
#      max-history: 7
